---
Name: 'seoextensions'
---
Page:
  extensions:
    - Hubertusanton\SilverStripeSeo\SeoObjectExtension
SiteConfig:
  extensions:
    - Hubertusanton\SilverStripeSeo\SeoSiteConfig

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - hubertusanton/silverstripe-seo:client/css/seo.css
  extra_requirements_javascript:
    - hubertusanton/silverstripe-seo:client/js/seo.js
    - hubertusanton/silverstripe-seo:client/js/GoogleSuggestField.js
